
# Wind API Example

This notebook demonstrates how to use the `wind` package to work with wind data download calendars.

## 1. Holiday Calendar Examples

In [1]:
%load_ext autoreload
%autoreload 2

# Import CBT (Chicago Board of Trade) holiday calendar
from my_holiday import CBT

# Create a CBT holiday calendar instance
cbt_holidays = CBT()

# Display the holiday calendar
print("CBT Holiday Calendar:")
print(cbt_holidays)

CBT Holiday Calendar:
{'country': None, 'expand': True, 'language': None, 'market': CBT, 'observed': True, 'subdiv': None, 'years': set()}

In [2]:
# You can also import other holiday calendars
from my_holiday import DCE, CZCE, ICE

# DCE (Dalian Commodity Exchange)
dce_holidays = DCE()
print("DCE Holiday Calendar:")
print(dce_holidays)

DCE Holiday Calendar:
{'country': None, 'expand': True, 'language': None, 'market': DCE, 'observed': True, 'subdiv': None, 'years': set()}

In [3]:
# Import utility functions for date calculations
from my_holiday import (
    is_holiday,
    next_business_day,
    previous_business_day,
    business_days_between,
    apply_date_rule,
    apply_date_rules
)

# Check if a date is a holiday
date_to_check = '2024-12-25'
print(f"Is {date_to_check} a holiday? {is_holiday(date_to_check, 'CBT')}")

# Get the next business day
next_biz = next_business_day('2024-12-25', 'CBT')
print(f"Next business day after 2024-12-25: {next_biz}")

Is 2024-12-25 a holiday? True
Next business day after 2024-12-25: 2024-12-26

In [4]:
# Apply date rules example
# Rule format: +/-<number><symbol>
# Symbols: B=business day, M=month, W=week, d=day, Q=quarter, Y=year

base_date = '2024-01-15'

# Get 5 business days before
result = apply_date_rule(base_date, '-5B', 'CBT')
print(f"5 business days before {base_date}: {result}")

# Get 1 month ahead
result = apply_date_rule(base_date, '+1M', 'CBT')
print(f"1 month after {base_date}: {result}")

# Apply multiple rules
result = apply_date_rules(base_date, '+1M-5B', 'CBT')
print(f"1 month minus 5 business days from {base_date}: {result}")

result = apply_date_rules(base_date, '-2Y', 'CBT')
print(f"2 years before {base_date}: {result}")

5 business days before 2024-01-15: 2024-01-08
1 month after 2024-01-15: 2024-02-15
1 month minus 5 business days from 2024-01-15: 2024-02-08
2 years before 2024-01-15: 2022-01-15

## 2. Commodity Information Examples

In [5]:
# Import from commodity package
from commodity import (
    commodity_helper,
    COMMODINFO,
    NUM_TO_MONTH,
    MONTH_TO_NUM
)

# Get commodity information
print("Available commodities:", list(COMMODINFO.keys()))

# Get a specific commodity
soybean = commodity_helper.get_commodity('S')
print(f"\nSoybean (S) info:")
print(f"  Holiday calendar: {soybean.holiday}")
print(f"  Currency: {soybean.currency}")
print(f"  Valid expiration: {soybean.valid_expiration}")

Available commodities: ['AK', 'BP', 'AE', 'SH', 'AC', 'PAL', 'LHD', 'ZRO', 'ZRR', 'ZRC', 'ZME', 'VOO', 'VV', 'VN', 'CB', 'S', 'SR', 'BO', 'SM', 'C', 'W', 'KW', 'CT', 'SB']

Soybean (S) info:
  Holiday calendar: CBT
  Currency: USD
  Valid expiration: FHKNQUX

## 3. Historical Contracts for DCE No.1 Soybean, CZCE White Sugar, CBT Soybean

In [6]:
# Create commodity instances for the three commodities
# AK = DCE No.1 Soybean
# CB = CZCE White Sugar (SR ticker)
# S = CBT Soybean

dce_soybean = commodity_helper.get_commodity('AK')  # DCE No.1 Soybean
czce_sugar = commodity_helper.get_commodity('CB')   # CZCE White Sugar
cbt_soybean = commodity_helper.get_commodity('S')   # CBT Soybean

print("Commodity Details:")
print(f"DCE No.1 Soybean (AK): holiday={dce_soybean.holiday}, valid_expiration={dce_soybean.valid_expiration}")
print(f"CZCE White Sugar (CB): holiday={czce_sugar.holiday}, valid_expiration={czce_sugar.valid_expiration}")
print(f"CBT Soybean (S): holiday={cbt_soybean.holiday}, valid_expiration={cbt_soybean.valid_expiration}")

Commodity Details:
DCE No.1 Soybean (AK): holiday=DCE, valid_expiration=FHKNUX
CZCE White Sugar (CB): holiday=CZCE, valid_expiration=FHKNUX
CBT Soybean (S): holiday=CBT, valid_expiration=FHKNQUX

In [7]:
# Get full historical contract list for each commodity
# Using a wide date range to get all contracts from 2000 to 2026

dce_soybean_contracts = dce_soybean.get_commodity_series('2000-01-01', '2026-12-31', cache_codes=True)
czce_sugar_contracts = czce_sugar.get_commodity_series('2000-01-01', '2026-12-31', cache_codes=True)
cbt_soybean_contracts = cbt_soybean.get_commodity_series('2000-01-01', '2026-12-31', cache_codes=True)

print(f"DCE No.1 Soybean contracts ({len(dce_soybean_contracts)} total):")
print(f"  First 5: {dce_soybean_contracts[:5]}")
print(f"  Last 5: {dce_soybean_contracts[-5:]}")
print()
print(f"CZCE White Sugar contracts ({len(czce_sugar_contracts)} total):")
print(f"  First 5: {czce_sugar_contracts[:5]}")
print(f"  Last 5: {czce_sugar_contracts[-5:]}")
print()
print(f"CBT Soybean contracts ({len(cbt_soybean_contracts)} total):")
print(f"  First 5: {cbt_soybean_contracts[:5]}")
print(f"  Last 5: {cbt_soybean_contracts[-5:]}")

DCE No.1 Soybean contracts (174 total):
  First 5: ['F99', 'H99', 'K99', 'N99', 'U99']
  Last 5: ['H27', 'K27', 'N27', 'U27', 'X27']

CZCE White Sugar contracts (174 total):
  First 5: ['F99', 'H99', 'K99', 'N99', 'U99']
  Last 5: ['H27', 'K27', 'N27', 'U27', 'X27']

CBT Soybean contracts (203 total):
  First 5: ['F99', 'H99', 'K99', 'N99', 'Q99']
  Last 5: ['K27', 'N27', 'Q27', 'U27', 'X27']

In [8]:
# Display contracts with their last trading days
# Get last trading days for each commodity

dce_ltd = dce_soybean.get_last_trading_days()
czce_ltd = czce_sugar.get_last_trading_days()
cbt_ltd = cbt_soybean.get_last_trading_days()

print("Sample of DCE No.1 Soybean contracts with last trading days:")
for contract in list(dce_ltd.items())[:5]:
    print(f"  {contract[0]}: {contract[1]}")
print()

print("Sample of CZCE White Sugar contracts with last trading days:")
for contract in list(czce_ltd.items())[:5]:
    print(f"  {contract[0]}: {contract[1]}")
print()

print("Sample of CBT Soybean contracts with last trading days:")
for contract in list(cbt_ltd.items())[:5]:
    print(f"  {contract[0]}: {contract[1]}")

Sample of DCE No.1 Soybean contracts with last trading days:
  F99: 1999-01-15
  H99: 1999-03-12
  K99: 1999-05-14
  N99: 1999-07-14
  U99: 1999-09-14

Sample of CZCE White Sugar contracts with last trading days:
  F99: 1999-01-15
  H99: 1999-03-12
  K99: 1999-05-14
  N99: 1999-07-14
  U99: 1999-09-14

Sample of CBT Soybean contracts with last trading days:
  F99: 1998-12-31
  H99: 1999-02-26
  K99: 1999-04-30
  N99: 1999-06-30
  Q99: 1999-07-30

## 4. Select Specific Contracts (Pre-2020 Expired and 2026 Expiring)

In [9]:
# Select one contract that expired before 2020 and one that expires in 2026
# Using N (July) contracts for consistency

# Contracts: N19 = July 2019 (expired before 2020)
#            N26 = July 2026 (expires in 2026)

pre_2020_contract = 'N19'  # July 2019
contract_2026 = 'N26'      # July 2026

# Generate Wind tickers and storage symbols for each commodity and contract
print("=" * 60)
print("Selected Contracts: Wind Tickers & Storage Symbols")
print("=" * 60)

print("\nPre-2020 Contract (expired before 2020):")
dce_pre2020_ticker = dce_soybean.generate_wind_ticker(pre_2020_contract)
czce_pre2020_ticker = czce_sugar.generate_wind_ticker(pre_2020_contract)
cbt_pre2020_ticker = cbt_soybean.generate_wind_ticker(pre_2020_contract)
dce_pre2020_storage = dce_soybean.generate_storage_symbol(pre_2020_contract)
czce_pre2020_storage = czce_sugar.generate_storage_symbol(pre_2020_contract)
cbt_pre2020_storage = cbt_soybean.generate_storage_symbol(pre_2020_contract)
print(f"  DCE No.1 Soybean {pre_2020_contract}: wind={dce_pre2020_ticker}, storage={dce_pre2020_storage}")
print(f"  CZCE White Sugar {pre_2020_contract}: wind={czce_pre2020_ticker}, storage={czce_pre2020_storage}")
print(f"  CBT Soybean {pre_2020_contract}: wind={cbt_pre2020_ticker}, storage={cbt_pre2020_storage}")

print("\n2026 Contract (expires in 2026):")
dce_2026_ticker = dce_soybean.generate_wind_ticker(contract_2026)
czce_2026_ticker = czce_sugar.generate_wind_ticker(contract_2026)
cbt_2026_ticker = cbt_soybean.generate_wind_ticker(contract_2026)
dce_2026_storage = dce_soybean.generate_storage_symbol(contract_2026)
czce_2026_storage = czce_sugar.generate_storage_symbol(contract_2026)
cbt_2026_storage = cbt_soybean.generate_storage_symbol(contract_2026)
print(f"  DCE No.1 Soybean {contract_2026}: wind={dce_2026_ticker}, storage={dce_2026_storage}")
print(f"  CZCE White Sugar {contract_2026}: wind={czce_2026_ticker}, storage={czce_2026_storage}")
print(f"  CBT Soybean {contract_2026}: wind={cbt_2026_ticker}, storage={cbt_2026_storage}")

============================================================
Selected Contracts: Wind Tickers & Storage Symbols
============================================================

Pre-2020 Contract (expired before 2020):
  DCE No.1 Soybean N19: wind=A1907.DCE, storage=AKN19
  CZCE White Sugar N19: wind=SR907.CZC, storage=CBN19
  CBT Soybean N19: wind=SN19E.CBT, storage=SN19

2026 Contract (expires in 2026):
  DCE No.1 Soybean N26: wind=A2607.DCE, storage=AKN26
  CZCE White Sugar N26: wind=SR607.CZC, storage=CBN26
  CBT Soybean N26: wind=SN26E.CBT, storage=SN26

In [10]:
# Get last trading days for selected contracts
print("=" * 60)
print("Last Trading Days for Selected Contracts")
print("=" * 60)

dce_pre2020_ltd = dce_soybean.last_trading_day(pre_2020_contract)
czce_pre2020_ltd = czce_sugar.last_trading_day(pre_2020_contract)
cbt_pre2020_ltd = cbt_soybean.last_trading_day(pre_2020_contract)

dce_2026_ltd = dce_soybean.last_trading_day(contract_2026)
czce_2026_ltd = czce_sugar.last_trading_day(contract_2026)
cbt_2026_ltd = cbt_soybean.last_trading_day(contract_2026)

print(f"\nPre-2020 Contract ({pre_2020_contract}):")
print(f"  DCE No.1 Soybean: {dce_pre2020_ltd}")
print(f"  CZCE White Sugar: {czce_pre2020_ltd}")
print(f"  CBT Soybean: {cbt_pre2020_ltd}")

print(f"\n2026 Contract ({contract_2026}):")
print(f"  DCE No.1 Soybean: {dce_2026_ltd}")
print(f"  CZCE White Sugar: {czce_2026_ltd}")
print(f"  CBT Soybean: {cbt_2026_ltd}")

============================================================
Last Trading Days for Selected Contracts
============================================================

Pre-2020 Contract (N19):
  DCE No.1 Soybean: 2019-07-12
  CZCE White Sugar: 2019-07-12
  CBT Soybean: 2019-06-28

2026 Contract (N26):
  DCE No.1 Soybean: 2026-07-14
  CZCE White Sugar: 2026-07-14
  CBT Soybean: 2026-06-30

In [11]:
# Calculate date range: 2 months before expiration
print("=" * 60)
print("Date Ranges for Data Query (2 months before expiration)")
print("=" * 60)

# Pre-2020 contracts
dce_pre2020_start = apply_date_rule(dce_pre2020_ltd, '-2M', dce_soybean.holiday)
czce_pre2020_start = apply_date_rule(czce_pre2020_ltd, '-2M', czce_sugar.holiday)
cbt_pre2020_start = apply_date_rule(cbt_pre2020_ltd, '-2M', cbt_soybean.holiday)

print(f"\nPre-2020 Contract ({pre_2020_contract}):")
print(f"  DCE No.1 Soybean: {dce_pre2020_start} to {dce_pre2020_ltd}")
print(f"  CZCE White Sugar: {czce_pre2020_start} to {czce_pre2020_ltd}")
print(f"  CBT Soybean: {cbt_pre2020_start} to {cbt_pre2020_ltd}")

# 2026 contracts
dce_2026_start = apply_date_rule(dce_2026_ltd, '-2M', dce_soybean.holiday)
czce_2026_start = apply_date_rule(czce_2026_ltd, '-2M', czce_sugar.holiday)
cbt_2026_start = apply_date_rule(cbt_2026_ltd, '-2M', cbt_soybean.holiday)

print(f"\n2026 Contract ({contract_2026}):")
print(f"  DCE No.1 Soybean: {dce_2026_start} to {dce_2026_ltd}")
print(f"  CZCE White Sugar: {czce_2026_start} to {czce_2026_ltd}")
print(f"  CBT Soybean: {cbt_2026_start} to {cbt_2026_ltd}")

============================================================
Date Ranges for Data Query (2 months before expiration)
============================================================

Pre-2020 Contract (N19):
  DCE No.1 Soybean: 2019-05-12 to 2019-07-12
  CZCE White Sugar: 2019-05-12 to 2019-07-12
  CBT Soybean: 2019-04-28 to 2019-06-28

2026 Contract (N26):
  DCE No.1 Soybean: 2026-05-14 to 2026-07-14
  CZCE White Sugar: 2026-05-14 to 2026-07-14
  CBT Soybean: 2026-04-30 to 2026-06-30

## 5. Query Data Using Wind API

In [12]:
# Import Wind API components
from data_api.wind import WindDownloader, WindPipeline, WindConfig

# Create configuration (uses default fields from WindConfig)
config = WindConfig(data_path='data/wind')

# Display default fields for futures
print("Default fields for futures (from WindConfig):")
print(f"  {config.future_fields}")
print()

# Create downloader and pipeline
downloader = WindDownloader(config.to_dict())
pipeline = WindPipeline(downloader, config.to_dict())

Default fields for futures (from WindConfig):
  ['open', 'high', 'low', 'close', 'volume', 'oi', 'settle']

In [13]:
# Connect to Wind Terminal
# NOTE: Wind Terminal must be running for this to work

if downloader.connect():
    print("Successfully connected to Wind Terminal")
else:
    print("Failed to connect to Wind Terminal. Make sure Wind Terminal is running.")

2026-04-08 17:46:04,778 - autoreload - ERROR - Failed to read module file 'C:\Wind\Wind.NET.Client\WindNET\x64\WindPy.py' for module 'WindPy': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\yuhang.hou\projects\my_backtest\my_backtest\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 30: invalid start byte

Welcome to use Wind Quant API for Python (WindPy)!

COPYRIGHT (C) 2024 WIND INFORMATION CO., LTD. ALL RIGHTS RESERVED.
IN NO CIRCUMSTANCE SHALL WIND BE RESPONSIBLE FOR ANY DAMAGES OR LOSSES CAUSED BY USING WIND QUANT API FOR Python.

2026-04-08 17:46:07,754 - data_api.wind.downloader - INFO - Successfully connected to Wind Terminal

Successfully connected to Wind Terminal

In [14]:
# Query data for Pre-2020 contracts
# Using fields=None will use the default future_fields from WindConfig

print("=" * 60)
print("Querying Pre-2020 Contract Data (2 months before expiration)")
print("=" * 60)

# DCE No.1 Soybean - Pre-2020
print(f"\nQuerying {dce_pre2020_ticker} -> {dce_pre2020_storage} from {dce_pre2020_start} to {dce_pre2020_ltd}")
dce_pre2020_result = pipeline.run_single(
    symbol=dce_pre2020_ticker,
    start_date=dce_pre2020_start,
    end_date=dce_pre2020_ltd,
    fields=None,  # Uses default future_fields
    save_to_disk=False,
    storage_symbol=dce_pre2020_storage
)

if dce_pre2020_result['success']:
    print(f"  Success! Data shape: {dce_pre2020_result['data'].shape}")
    print(f"  Columns: {list(dce_pre2020_result['data'].columns)}")
    display(dce_pre2020_result['data'].head())
else:
    print(f"  Failed: {dce_pre2020_result['error']}")

2026-04-08 17:46:07,824 - data_api.wind.pipeline - INFO - Processing A1907.DCE -> AKN19 (1/1)
2026-04-08 17:46:07,825 - data_api.wind.downloader - INFO - Fetching A1907.DCE from 2019-05-12 to 2019-07-12 (attempt 1)

============================================================
Querying Pre-2020 Contract Data (2 months before expiration)
============================================================

Querying A1907.DCE -> AKN19 from 2019-05-12 to 2019-07-12
A1907.DCE open,high,low,close,volume,oi,settle 2019-05-12 2019-07-12

2026-04-08 17:46:08,479 - data_api.wind.downloader - INFO - Fetched 44 records for A1907.DCE

  Success! Data shape: (44, 8)
  Columns: ['open', 'high', 'low', 'close', 'volume', 'oi', 'settle', 'symbol']

              open    high     low   close  volume     oi  settle symbol
date
2019-05-13  3443.0  3443.0  3381.0  3396.0    44.0  312.0  3404.0  AKN19
2019-05-14  3387.0  3514.0  3361.0  3462.0   542.0  238.0  3421.0  AKN19
2019-05-15  3481.0  3482.0  3472.0  3472.0    10.0  238.0  3478.0  AKN19
2019-05-16  3502.0  3523.0  3477.0  3510.0   270.0  442.0  3510.0  AKN19
2019-05-17  3488.0  3506.0  3485.0  3501.0    48.0  448.0  3497.0  AKN19

In [15]:
# CZCE White Sugar - Pre-2020
print(f"\nQuerying {czce_pre2020_ticker} -> {czce_pre2020_storage} from {czce_pre2020_start} to {czce_pre2020_ltd}")
czce_pre2020_result = pipeline.run_single(
    symbol=czce_pre2020_ticker,
    start_date=czce_pre2020_start,
    end_date=czce_pre2020_ltd,
    fields=None,  # Uses default future_fields
    save_to_disk=False,
    storage_symbol=czce_pre2020_storage
)

if czce_pre2020_result['success']:
    print(f"  Success! Data shape: {czce_pre2020_result['data'].shape}")
    print(f"  Columns: {list(czce_pre2020_result['data'].columns)}")
    display(czce_pre2020_result['data'].head())
else:
    print(f"  Failed: {czce_pre2020_result['error']}")

2026-04-08 17:46:08,581 - data_api.wind.pipeline - INFO - Processing SR907.CZC -> CBN19 (1/1)
2026-04-08 17:46:08,583 - data_api.wind.downloader - INFO - Fetching SR907.CZC from 2019-05-12 to 2019-07-12 (attempt 1)

Querying SR907.CZC -> CBN19 from 2019-05-12 to 2019-07-12
SR907.CZC open,high,low,close,volume,oi,settle 2019-05-12 2019-07-12

2026-04-08 17:46:09,101 - data_api.wind.downloader - INFO - Fetched 44 records for SR907.CZC

  Success! Data shape: (44, 8)
  Columns: ['open', 'high', 'low', 'close', 'volume', 'oi', 'settle', 'symbol']

              open    high     low   close  volume     oi  settle symbol
date
2019-05-13  5150.0  5151.0  5150.0  5151.0     6.0  480.0  5150.0  CBN19
2019-05-14  5142.0  5151.0  5011.0  5062.0    94.0  480.0  5056.0  CBN19
2019-05-15     NaN     NaN     NaN  5081.0     0.0  480.0  5081.0  CBN19
2019-05-16  5080.0  5135.0  5077.0  5132.0    30.0  474.0  5112.0  CBN19
2019-05-17  5131.0  5148.0  5070.0  5070.0    48.0  496.0  5096.0  CBN19

In [16]:
# CBT Soybean - Pre-2020
print(f"\nQuerying {cbt_pre2020_ticker} -> {cbt_pre2020_storage} from {cbt_pre2020_start} to {cbt_pre2020_ltd}")
cbt_pre2020_result = pipeline.run_single(
    symbol=cbt_pre2020_ticker,
    start_date=cbt_pre2020_start,
    end_date=cbt_pre2020_ltd,
    fields=None,  # Uses default future_fields
    save_to_disk=False,
    storage_symbol=cbt_pre2020_storage
)

if cbt_pre2020_result['success']:
    print(f"  Success! Data shape: {cbt_pre2020_result['data'].shape}")
    print(f"  Columns: {list(cbt_pre2020_result['data'].columns)}")
    display(cbt_pre2020_result['data'].head())
else:
    print(f"  Failed: {cbt_pre2020_result['error']}")

2026-04-08 17:46:09,183 - data_api.wind.pipeline - INFO - Processing SN19E.CBT -> SN19 (1/1)
2026-04-08 17:46:09,184 - data_api.wind.downloader - INFO - Fetching SN19E.CBT from 2019-04-28 to 2019-06-28 (attempt 1)

Querying SN19E.CBT -> SN19 from 2019-04-28 to 2019-06-28
SN19E.CBT open,high,low,close,volume,oi,settle 2019-04-28 2019-06-28

2026-04-08 17:46:09,646 - data_api.wind.downloader - INFO - Fetched 41 records for SN19E.CBT

  Success! Data shape: (41, 8)
  Columns: ['open', 'high', 'low', 'close', 'volume', 'oi', 'settle', 'symbol']

              open    high     low   close    volume        oi  settle symbol
date
2019-04-29  868.25  873.00  860.50  861.25  157011.0  406187.0  860.75   SN19
2019-04-30  861.25  864.50  851.25  854.00  114479.0  410448.0  854.00   SN19
2019-05-06  828.00  834.00  816.75  830.25  147134.0  436077.0  830.25   SN19
2019-05-07  829.00  836.25  827.00  830.25   97120.0  433280.0  830.75   SN19
2019-05-08  830.75  835.00  824.75  825.25   88765.0  423921.0  827.25   SN19

In [17]:
# Query data for 2026 contracts

print("=" * 60)
print("Querying 2026 Contract Data (2 months before expiration)")
print("=" * 60)

# DCE No.1 Soybean - 2026
print(f"\nQuerying {dce_2026_ticker} -> {dce_2026_storage} from {dce_2026_start} to {dce_2026_ltd}")
dce_2026_result = pipeline.run_single(
    symbol=dce_2026_ticker,
    start_date=dce_2026_start,
    end_date=dce_2026_ltd,
    fields=None,  # Uses default future_fields
    save_to_disk=False,
    storage_symbol=dce_2026_storage
)

if dce_2026_result['success']:
    print(f"  Success! Data shape: {dce_2026_result['data'].shape}")
    print(f"  Columns: {list(dce_2026_result['data'].columns)}")
    display(dce_2026_result['data'].head())
else:
    print(f"  Failed: {dce_2026_result['error']}")

2026-04-08 17:46:09,718 - data_api.wind.pipeline - INFO - Processing A2607.DCE -> AKN26 (1/1)
2026-04-08 17:46:09,719 - data_api.wind.downloader - INFO - Fetching A2607.DCE from 2026-05-14 to 2026-07-14 (attempt 1)

============================================================
Querying 2026 Contract Data (2 months before expiration)
============================================================

Querying A2607.DCE -> AKN26 from 2026-05-14 to 2026-07-14
A2607.DCE open,high,low,close,volume,oi,settle 2026-05-14 2026-07-14

2026-04-08 17:46:10,177 - data_api.wind.downloader - INFO - Fetched 43 records for A2607.DCE

  Success! Data shape: (43, 8)
  Columns: ['open', 'high', 'low', 'close', 'volume', 'oi', 'settle', 'symbol']

            open  high  low   close  volume  oi  settle symbol
date
2026-05-14   NaN   NaN  NaN  4653.0     NaN NaN  4658.0  AKN26
2026-05-15   NaN   NaN  NaN  4653.0     NaN NaN  4658.0  AKN26
2026-05-18   NaN   NaN  NaN  4653.0     NaN NaN  4658.0  AKN26
2026-05-19   NaN   NaN  NaN  4653.0     NaN NaN  4658.0  AKN26
2026-05-20   NaN   NaN  NaN  4653.0     NaN NaN  4658.0  AKN26

In [18]:
# CZCE White Sugar - 2026
print(f"\nQuerying {czce_2026_ticker} -> {czce_2026_storage} from {czce_2026_start} to {czce_2026_ltd}")
czce_2026_result = pipeline.run_single(
    symbol=czce_2026_ticker,
    start_date=czce_2026_start,
    end_date=czce_2026_ltd,
    fields=None,  # Uses default future_fields
    save_to_disk=False,
    storage_symbol=czce_2026_storage
)

if czce_2026_result['success']:
    print(f"  Success! Data shape: {czce_2026_result['data'].shape}")
    print(f"  Columns: {list(czce_2026_result['data'].columns)}")
    display(czce_2026_result['data'].head())
else:
    print(f"  Failed: {czce_2026_result['error']}")

2026-04-08 17:46:10,255 - data_api.wind.pipeline - INFO - Processing SR607.CZC -> CBN26 (1/1)
2026-04-08 17:46:10,256 - data_api.wind.downloader - INFO - Fetching SR607.CZC from 2026-05-14 to 2026-07-14 (attempt 1)

Querying SR607.CZC -> CBN26 from 2026-05-14 to 2026-07-14
SR607.CZC open,high,low,close,volume,oi,settle 2026-05-14 2026-07-14

2026-04-08 17:46:10,724 - data_api.wind.downloader - INFO - Fetched 43 records for SR607.CZC

  Success! Data shape: (43, 8)
  Columns: ['open', 'high', 'low', 'close', 'volume', 'oi', 'settle', 'symbol']

            open  high  low   close  volume  oi  settle symbol
date
2026-05-14   NaN   NaN  NaN  5292.0     NaN NaN  5304.0  CBN26
2026-05-15   NaN   NaN  NaN  5292.0     NaN NaN  5304.0  CBN26
2026-05-18   NaN   NaN  NaN  5292.0     NaN NaN  5304.0  CBN26
2026-05-19   NaN   NaN  NaN  5292.0     NaN NaN  5304.0  CBN26
2026-05-20   NaN   NaN  NaN  5292.0     NaN NaN  5304.0  CBN26

In [19]:
# CBT Soybean - 2026
print(f"\nQuerying {cbt_2026_ticker} -> {cbt_2026_storage} from {cbt_2026_start} to {cbt_2026_ltd}")
cbt_2026_result = pipeline.run_single(
    symbol=cbt_2026_ticker,
    start_date=cbt_2026_start,
    end_date=cbt_2026_ltd,
    fields=None,  # Uses default future_fields
    save_to_disk=False,
    storage_symbol=cbt_2026_storage
)

if cbt_2026_result['success']:
    print(f"  Success! Data shape: {cbt_2026_result['data'].shape}")
    print(f"  Columns: {list(cbt_2026_result['data'].columns)}")
    display(cbt_2026_result['data'].head())
else:
    print(f"  Failed: {cbt_2026_result['error']}")

2026-04-08 17:46:10,796 - data_api.wind.pipeline - INFO - Processing SN26E.CBT -> SN26 (1/1)
2026-04-08 17:46:10,796 - data_api.wind.downloader - INFO - Fetching SN26E.CBT from 2026-04-30 to 2026-06-30 (attempt 1)

Querying SN26E.CBT -> SN26 from 2026-04-30 to 2026-06-30
SN26E.CBT open,high,low,close,volume,oi,settle 2026-04-30 2026-06-30

2026-04-08 17:46:11,267 - data_api.wind.downloader - INFO - Fetched 40 records for SN26E.CBT

  Success! Data shape: (40, 8)
  Columns: ['open', 'high', 'low', 'close', 'volume', 'oi', 'settle', 'symbol']

            open  high  low   close  volume  oi  settle symbol
date
2026-04-30   NaN   NaN  NaN  1174.0     NaN NaN  1174.5   SN26
2026-05-06   NaN   NaN  NaN  1174.0     NaN NaN  1174.5   SN26
2026-05-07   NaN   NaN  NaN  1174.0     NaN NaN  1174.5   SN26
2026-05-08   NaN   NaN  NaN  1174.0     NaN NaN  1174.5   SN26
2026-05-11   NaN   NaN  NaN  1174.0     NaN NaN  1174.5   SN26

In [20]:
# Summary of all queries
print("=" * 60)
print("Summary of Data Queries")
print("=" * 60)

results = {
    'DCE No.1 Soybean (N19)': dce_pre2020_result,
    'CZCE White Sugar (N19)': czce_pre2020_result,
    'CBT Soybean (N19)': cbt_pre2020_result,
    'DCE No.1 Soybean (N26)': dce_2026_result,
    'CZCE White Sugar (N26)': czce_2026_result,
    'CBT Soybean (N26)': cbt_2026_result,
}

for name, result in results.items():
    status = "✓ Success" if result['success'] else f"✗ Failed: {result['error']}"
    shape = result['data'].shape if result['success'] else 'N/A'
    print(f"{name}: {status} (shape: {shape})")

============================================================
Summary of Data Queries
============================================================
DCE No.1 Soybean (N19): ✓ Success (shape: (44, 8))
CZCE White Sugar (N19): ✓ Success (shape: (44, 8))
CBT Soybean (N19): ✓ Success (shape: (41, 8))
DCE No.1 Soybean (N26): ✓ Success (shape: (43, 8))
CZCE White Sugar (N26): ✓ Success (shape: (43, 8))
CBT Soybean (N26): ✓ Success (shape: (40, 8))

In [21]:
import pandas as pd
from WindPy import w
def data_to_df(return_query):
    data = {}
    data['date'] = return_query.Times
    for col in range(len(return_query.Fields)): #df.Fields:
        data[return_query.Fields[col]] = return_query.Data[col]
    final_df = pd.DataFrame(data)
    return final_df


print(data_to_df(w.wsd("A2605.DCE", "firstradeday_s,ftdate,startdate,ftdate_new", "2026-03-12", "2026-03-13", "TradingCalendar=DCE")))

print(data_to_df(w.wsd("A2609.DCE", "firstradeday_s,ftdate,startdate,ftdate_new", "2026-03-12", "2026-03-13", "TradingCalendar=DCE")))

print(data_to_df(w.wsd("A2611.DCE", "firstradeday_s,ftdate,startdate,ftdate_new", "2026-03-12", "2026-03-13", "TradingCalendar=DCE")))

print(data_to_df(w.wsd("A2607.DCE", "firstradeday_s,ftdate,startdate,ftdate_new", "2026-03-12", "2026-03-13", "TradingCalendar=DCE")))

print(data_to_df(w.wsd("A2701.DCE", "firstradeday_s,ftdate,startdate,ftdate_new", "2026-03-12", "2026-03-13", "TradingCalendar=DCE")))

print(data_to_df(w.wsd("A2703.DCE", "firstradeday_s,ftdate,startdate,ftdate_new", "2026-03-12", "2026-03-13", "TradingCalendar=DCE")))

         date FIRSTRADEDAY_S     FTDATE STARTDATE FTDATE_NEW
0  2026-03-12           None 2025-05-20      None 2025-05-20
1  2026-03-13           None 2025-05-20      None 2025-05-20
         date FIRSTRADEDAY_S     FTDATE STARTDATE FTDATE_NEW
0  2026-03-12           None 2025-09-15      None 2025-09-15
1  2026-03-13           None 2025-09-15      None 2025-09-15
         date FIRSTRADEDAY_S     FTDATE STARTDATE FTDATE_NEW
0  2026-03-12           None 2025-11-17      None 2025-11-17
1  2026-03-13           None 2025-11-17      None 2025-11-17
         date FIRSTRADEDAY_S     FTDATE STARTDATE FTDATE_NEW
0  2026-03-12           None 2025-07-15      None 2025-07-15
1  2026-03-13           None 2025-07-15      None 2025-07-15
         date FIRSTRADEDAY_S     FTDATE STARTDATE FTDATE_NEW
0  2026-03-12           None 2026-01-19      None 2026-01-19
1  2026-03-13           None 2026-01-19      None 2026-01-19
         date FIRSTRADEDAY_S     FTDATE STARTDATE FTDATE_NEW
0  2026-03-12           None 2026-03-16      None 2026-03-16
1  2026-03-13           None 2026-03-16      None 2026-03-16